diff --git a/zwavejs2mqtt/Dockerfile b/zwavejs2mqtt/Dockerfile
index 63ca649..b9f5f9c 100755
--- a/zwavejs2mqtt/Dockerfile
+++ b/zwavejs2mqtt/Dockerfile
@@ -20,13 +20,13 @@ RUN \
     && apk add --no-cache \
         eudev=3.2.11_pre1-r0 \
         libusb=1.0.24-r3 \
-        nginx=1.20.2-r0 \
+        nginx=1.20.2-r1 \
         nodejs=16.14.2-r0 \
     \
     && npm install --global yarn@2.4.3 \
     \
     && curl -J -L -o /tmp/zwavejs2mqtt.tar.gz \
-        "https://github.com/zwave-js/zwavejs2mqtt/archive/v6.7.2.tar.gz" \
+        $(curl -s https://api.github.com/repos/zwave-js/zwavejs2mqtt/releases/latest | jq -r '.tarball_url') \
     && tar zxvf \
         /tmp/zwavejs2mqtt.tar.gz \
         --strip 1 -C /opt \
@@ -40,6 +40,31 @@ RUN \
     && yarn remove \
         $(jq -r '.devDependencies | keys | join(" ")' package.json) \
     && yarn cache clean \
+    && true
+
+# Rebuild node-zwave-js with patch
+COPY node-zwave-js_zl7432.patch /tmp/
+
+RUN \
+    export ZWJS="https://github.com/zwave-js/node-zwave-js/archive/refs/tags/v$(node -p "require('/opt/node_modules/zwave-js/package.json').version").tar.gz" \
+    && mkdir /tmp/node-zwave-js \
+    && curl -J -L -o /tmp/node-zwave-js.tar.gz ${ZWJS} \
+    && tar zxvf \
+        /tmp/node-zwave-js.tar.gz \
+        --strip 1 -C /tmp/node-zwave-js \
+    \
+    && cd /tmp/node-zwave-js \
+    && patch -p0  < /tmp/node-zwave-js_zl7432.patch \
+    \
+    && yarn \
+    && yarn run build
+
+RUN true \
+    && cp -v /tmp/node-zwave-js/packages/config/config/devices/0x0109/zl7432.json /opt/node_modules/@zwave-js/config/config/devices/0x0109/zl7432.json \
+    && cp -v /tmp/node-zwave-js/packages/config/build/devices/CompatConfig* /opt/node_modules/@zwave-js/config/build/devices/ \
+    && cp -v /tmp/node-zwave-js/packages/zwave-js/build/lib/node/Node.* /opt/node_modules/zwave-js/build/lib/node/
+
+RUN true \
     \
     && npm uninstall -g yarn \
     && apk del --no-cache --purge .build-dependencies \
